export const LOGIN_USER = "LOGIN_USER";
export const STUDENT_GET = "STUDENT_GET";

export const ATTENDANCE_GET = "ATTENDANCE_DELETE";
export const ATTENDANCE_DELETE = "ATTENDANCE_DELETE";
export const ATTENDANCE_PATCH = "ATTENDANCE_PATCH";
export const ATTENDANCESTATE_PATCH = "ATTENDANCESTATE_PATCH";
